#!/bin/bash

# ipblink -- Blink the IP address on internal LED
# Copyright (C) 2019 Grant NIchol
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

dotLength=0.4
dashLength=$(echo "scale=2; $dotLength * 3" | bc)
charPause=$(echo "scale=2; $dotLength * 3 - $dotLength" | bc)
wordPause=$(echo "scale=2; $dotLength * 7 - $dashLength" | bc)

function onLed() {
	echo 0 > /sys/class/leds/led0/brightness
}

function offLed() {
	echo 1 > /sys/class/leds/led0/brightness
}

function morse_sendChar() {
code=$1
for ((codeChar=0;codeChar<${#code};codeChar++)); do
	case ${code:$codeChar:1} in
		".")
			onLed
			sleep $dotLength
			;;
		"-")
			onLed
			sleep $dashLength
			;;
	esac
	offLed
	sleep $dotLength
done
sleep $charPause
}

function morse_sendString() {
string=$1
for ((stringChar=0;stringChar<${#string};stringChar++)); do
	case ${string:$stringChar:1} in
		"1") morse_sendChar ".----" ;;
		"2") morse_sendChar "..---" ;;
		"3") morse_sendChar "...--" ;;
		"4") morse_sendChar "....-" ;;
		"5") morse_sendChar "....." ;;
		"6") morse_sendChar "-...." ;;
		"7") morse_sendChar "--..." ;;
		"8") morse_sendChar "---.." ;;
		"9") morse_sendChar "----." ;;
		"0") morse_sendChar "-----" ;;
		".") morse_sendChar ".-.-.-" ;;
		" ") sleep $wordPause ;;
	esac
	offLed
done
sleep $wordPause
} 

offLed
while [ 1=1 ]; do
sleep $(echo "scale=2; $dotLength * 10" | bc)
morse_sendString $(hostname -i)
done
